### PR TITLE
Fixate node version to 8.x

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma/issues/46

### CODE REVIEW

**Comment by ronaldtse** [comment]
Why do we do this?

**Comment by CAMOBAP795** [comment]
@opoudjis  Because this gem require puppeteer, and previously we had errors in travis-ci like this https://travis-ci.org/metanorma/metanorma-csd/jobs/516878858#L2156 

IDK why build was success regardless these errors

**Comment by ronaldtse** [comment]
So the failure here is real:

```
       @@ -1,2 +1,2 @@
       -{:accesseddate=>"XXX", :authors=>["Fred Flintstone", "Barney Rubble"], :authors_affiliations=>{""=>["Fred Flintstone"], "Bedrock Inc."=>["Barney Rubble"]}, :confirmeddate=>"XXX", :createddate=>"XXX", :docnumber=>"CC/WD 1000:2001", :doctitle=>"Main Title", :doctype=>"Standard", :docyear=>"2001", :draft=>"3.4", :draftinfo=>" (draft 3.4, 2000-01-01)", :edition=>"2", :editorialgroup=>[], :ics=>"XXX", :implementeddate=>"XXX", :issueddate=>"XXX", :obsoleteddate=>"XXX", :obsoletes=>nil, :obsoletes_part=>nil, :publisheddate=>"XXX", :receiveddate=>"XXX", :revdate=>"2000-01-01", :roles_authors_affiliations=>{"author"=>{"Bedrock Inc."=>["Barney Rubble"]}, "editor"=>{""=>["Fred Flintstone"]}}, :sc=>"XXXX", :secretariat=>"XXXX", :status=>"Working Draft", :tc=>"TC", :unpublished=>true, :updateddate=>"XXX", :wg=>"XXXX"}
       +{:accesseddate=>"XXX", :authors=>["Fred Flintstone", "Barney Rubble"], :authors_affiliations=>{""=>["Fred Flintstone", "Barney Rubble"]}, :confirmeddate=>"XXX", :createddate=>"XXX", :docnumber=>"CC/WD 1000:2001", :doctitle=>"Main Title", :doctype=>"Standard", :docyear=>"2001", :draft=>"3.4", :draftinfo=>" (draft 3.4, 2000-01-01)", :edition=>"2", :editorialgroup=>[], :ics=>"XXX", :implementeddate=>"XXX", :issueddate=>"XXX", :obsoleteddate=>"XXX", :obsoletes=>nil, :obsoletes_part=>nil, :publisheddate=>"XXX", :receiveddate=>"XXX", :revdate=>"2000-01-01", :roles_authors_affiliations=>{"author"=>{""=>["Barney Rubble"]}, "editor"=>{""=>["Fred Flintstone"]}}, :sc=>"XXXX", :secretariat=>"XXXX", :status=>"Working Draft", :tc=>"TC", :unpublished=>true, :updateddate=>"XXX", :wg=>"XXXX"}
```

**Comment by CAMOBAP795** [comment]
@ronaldtse I 99% sure that this will be fixed once `isodoc` will be updated, because of latest `isodoc` handle `organization` instead `org` https://github.com/metanorma/isodoc/blob/master/lib/isodoc/metadata.rb#L51

So, in my opinion, it's safe to merge this PR, but of course last work for @opoudjis

**Comment by opoudjis** [comment]
Yes, org > organization was an error in isodoc, and has now been fixed. I will do a release once I have worked through the backlog of the last few days.

**Pull request merged**
